using BestFor.Domain.Interfaces;
using BestFor.Dto;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BestFor.Domain.Entities
{
    /// <summary>
    /// Represents the item from the help page
    /// </summary>
    public class HelpItem : EntityBase, IDtoConvertable<HelpItemDto>
    {
        /// <summary>
        /// Autogenerated database identity Id. Not quite used
        /// </summary>
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public override int Id { get; set; }

        /// <summary>
        /// Unique string name. Example "Site Title".
        /// </summary>
        [Required]
        [StringLength(20, MinimumLength = 4)]
        public string Key { get; set; }

        /// <summary>
        /// Name of the culture the string is for. Example en-US
        /// </summary>
        [Required]
        [StringLength(5, MinimumLength = 4)]
        public string CultureName { get; set; }

        [Required]
        [StringLength(500, MinimumLength = 4)]
        public string HelpTitle { get; set; }

        /// <summary>
        /// Value in this language.
        /// </summary>
        [Required]
        public string Value { get; set; }

        public HelpItemDto ToDto()
        {
            return new HelpItemDto()
            {
                Id = Id,
                Key = Key,
                CultureName = CultureName,
                Value = Value,
                HelpTitle = HelpTitle
            };
        }
        public int FromDto(HelpItemDto dto)
        {
            Id = dto.Id;
            Key = dto.Key;
            CultureName = dto.CultureName;
            Value = dto.Value;
            HelpTitle = dto.HelpTitle;

            return Id;
        }
    }
}
